CREATE TABLE IF NOT EXISTS usuarios (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  senha_hash TEXT NOT NULL,
  tipo TEXT CHECK(tipo IN ('admin', 'cliente')) NOT NULL DEFAULT 'cliente'
);

CREATE TABLE IF NOT EXISTS caixas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL,
  usuario_id INTEGER DEFAULT NULL,
  FOREIGN KEY(usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE IF NOT EXISTS niveis (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  caixa_id INTEGER NOT NULL,
  caixa1 REAL,
  caixa2 REAL,
  bomba INTEGER,
  data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(caixa_id) REFERENCES caixas(id)
);

CREATE TABLE IF NOT EXISTS chamados (
  id SERIAL PRIMARY KEY,
  usuario_id INT REFERENCES usuarios(id) ON DELETE CASCADE,
  assunto VARCHAR(150) NOT NULL,
  mensagem TEXT NOT NULL,
  status VARCHAR(20) DEFAULT 'Pendente',
  data TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);